### ISSUE TITLE
 fails silently after selecting zipfile, path and filename errors in console,

### ISSUE THREAD

**Issue by MarkPearce** [Superkikim/obsidian-chatgpt-import#1]
Sounds like a great idea! would be excellent.  I couldn't get it to work though.
I downloaded the zip in releases, installed and activated the plug in.... run the import command, select zip. then silent fail. with many filepath errors.  (loglfile and example below)

[obsidian.md-1700881218721.log](https://github.com/Superkikim/obsidian-chatgpt-import/files/13462914/obsidian.md-1700881218721.log)

Error creating folder: Error: File name cannot contain any of the following characters: * " \ / < > : | ?
    at jy (app.js:1:696095)
    at t.checkPath (app.js:1:703345)
    at t.<anonymous> (app.js:1:706008)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at app.js:1:236048
    at new Promise (<anonymous>)
    at v (app.js:1:235793)
    at t.createFolder (app.js:1:705896)
    at ChatGPTImportPlugin.handleZipFile (plugin:obsidian-chatgpt-import:2773:28)
handleZipFile @ plugin:obsidian-chatgpt-import:2775

**Comment by Superkikim** [comment]
What is your operating system ?This is a good point I guess. I use Linux and I didn't test any other. Most probably I should make a method to convert note names to an acceptable string for any file system.Le 25 nov. 2023 à 04:05, MarkPearce ***@***.***> a écrit :﻿
Sounds like a great idea! would be excellent.  I couldn't get it to work though.
I downloaded the zip in releases, installed and activated the plug in.... run the import command, select zip. then silent fail. with many filepath errors.  (loglfile and example below)
obsidian.md-1700881218721.log
Error creating folder: Error: File name cannot contain any of the following characters: * " \ / < > : | ?
at jy (app.js:1:696095)
at t.checkPath (app.js:1:703345)
at t. (app.js:1:706008)
at app.js:1:237027
at Object.next (app.js:1:237132)
at app.js:1:236048
at new Promise ()
at v (app.js:1:235793)
at t.createFolder (app.js:1:705896)
at ChatGPTImportPlugin.handleZipFile (plugin:obsidian-chatgpt-import:2773:28)
handleZipFile @ plugin:obsidian-chatgpt-import:2775

**Comment by Superkikim** [comment]
Can you provide me some converstion title examples with special caracters in you chats ?Le 25 nov. 2023 à 04:05, MarkPearce ***@***.***> a écrit :﻿
Sounds like a great idea! would be excellent.  I couldn't get it to work though.
I downloaded the zip in releases, installed and activated the plug in.... run the import command, select zip. then silent fail. with many filepath errors.  (loglfile and example below)
obsidian.md-1700881218721.log
Error creating folder: Error: File name cannot contain any of the following characters: * " \ / < > : | ?
at jy (app.js:1:696095)
at t.checkPath (app.js:1:703345)
at t. (app.js:1:706008)
at app.js:1:237027
at Object.next (app.js:1:237132)
at app.js:1:236048
at new Promise ()
at v (app.js:1:235793)
at t.createFolder (app.js:1:705896)
at ChatGPTImportPlugin.handleZipFile (plugin:obsidian-chatgpt-import:2773:28)
handleZipFile @ plugin:obsidian-chatgpt-import:2775

**Comment by MarkPearce** [comment]
Windows 10, I'll try it on my mac today for comparison.

here's the export from chatgpt
[96a633c90e5bb21e1be8665893fc91375102566f8f56719a1ef62e325b0e5822-2023-11-25-02-30-00.zip](https://github.com/Superkikim/obsidian-chatgpt-import/files/13464283/96a633c90e5bb21e1be8665893fc91375102566f8f56719a1ef62e325b0e5822-2023-11-25-02-30-00.zip)

if the chat names are the become file names i don't have any special characters there,,, unless space is one.

I am using a GPT created by uploading a pdf, and that often reads poorly and leads to messy data.
![image](https://github.com/Superkikim/obsidian-chatgpt-import/assets/6976378/9f2635bf-49e2-428b-9974-b564f701db4d)

**Comment by MarkPearce** [comment]
Doesn't seem to be the chat names, I removed all the ones with : in it.  Maybe the Dalle image responses?

**Comment by Superkikim** [comment]
Don't worry too much. I made a lot of changes. I'm testing it on Windows and I will also test on iPad. I'll push a new release soon.Le 25 nov. 2023 à 15:10, MarkPearce ***@***.***> a écrit :﻿
Windows 10, I'll try it on my mac today for comparison.
here's the export from chatgpt
96a633c90e5bb21e1be8665893fc91375102566f8f56719a1ef62e325b0e5822-2023-11-25-02-30-00.zip
if the chat names are the become file names i don't have any special characters there,,, unless space is one.
I am using a GPT created by uploading a pdf, and that often reads poorly and leads to messy data.
image.png (view on web)

**Comment by Superkikim** [comment]
Would you be kind enough to try the latest commit on master branch ? 

In this commit, I sanitize notes filename, and I ensure two notes with same title get different file name.

**Comment by MarkPearce** [comment]
Works!  organizes the chats into folders by date (i guess that is from the export) Thanks for making the tool.
![Capture](https://github.com/Superkikim/obsidian-chatgpt-import/assets/6976378/0e7af085-f049-43e0-9961-cf819cbe3355)

**Comment by Superkikim** [comment]
Yes. The plugin check the converstion created date and the note is created in the YYYY/MM folder accordingly. Still have to work on updates (add new messages to already imported notes and update last update date). Seems not to work properly right for now. If you have other ideas or suggestions on features let me knowY I don't make promises but I can try implement.O'll try to publish a new release next weekLe 6 déc. 2023 à 23:02, MarkPearce ***@***.***> a écrit :﻿
Works!  organizes the chats into folders by date (i guess that is from the export) Thanks for making the tool.
Capture.PNG (view on web)

**Comment by Kmfernan5** [comment]
Is there a way to fix the dates?

**Comment by Superkikim** [comment]
> Is there a way to fix the dates?

Hi. Can you be more specific ? What issue do you have with dates ?

**Comment by Kmfernan5** [comment]
Id like for the file name to be appended by date YYYY-MM-DD create date. easier to find similar notes.

**Comment by Superkikim** [comment]
I can do that. Let me get back to it. It's about time.

**Comment by Superkikim** [comment]
@MarkPearce I'm working on making tests on the zip file, and improving error handling all together.
