### ISSUE TITLE
Windows 10 Can't Select Zip file

### ISSUE THREAD

**Issue by dsaldivar** [Superkikim/obsidian-chatgpt-import#2]
I'm having an issue not being able to select the zip file in the Open Dialog windows.  If I issue the command in Obsidian to import Chatgpt an Explorer Window appears allowing to select the zip file. However if you click on the zip file it doesn't select it on the open file name area.

**Comment by Superkikim** [comment]
Hi. I didn't see this issue so far. Sorry.  I thought that was addressed. Can you confirm it still doesn't work ?
