### ISSUE TITLE
Bundle and minification

### ISSUE THREAD

**Issue by jfloodnet** [Superkikim/obsidian-chatgpt-import#4]
Im not familiar with buidling obsidian plugins, but is it possible to get plug bundled and minified? 

The plugin zip currently has 5100 objects in it due to the node_modules being included.

**Comment by jfloodnet** [comment]
Ok I see you've actually got a main.js which is bundled, but the zip has zipped everything.

What's the essential files for the plugin? Can we remove the rest from the zip?

**Comment by Superkikim** [comment]
Indeed, I've checked it out. I can add nodejs on gitignore and create a new release. I have to test that.

**Comment by jfloodnet** [comment]
Yep cool, I tested out just included the data file main.js and the manifest and that seem to work fine for me.
